### PR TITLE
removed fuel_tile background from the html output, added savanna to the PDF output, fixed TM signs

### PR DESCRIPTION
**Pull request by svekars**
...PDF output, fixed TM signs

### CODE REVIEW

**Comment by mihgen** [comment]
Please rebase - I merged your previous commit. Please follow commit messages recommendations: limit the length of first line. This is great article about it: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by svekars** [comment]
Misha, 

Dmitry Borodaenko helped me to rebase today. For some reason, the changes from that merge are not there.

**Comment by mihgen** [comment]
I merged this: https://github.com/Mirantis/fuel-docs/pull/30/files

Rebase is still required - Merge button is not available. The difference I see between master is fuel_title.jpg, and pdf docs - other changes are already in master.

**Comment by mihgen** [comment]
+1

**Pull request merged**
